### ISSUE TITLE
UPDATEJOB jobid value [options] 

### ISSUE THREAD

**Issue by clamoriniere** [antirez/disque#45]
First of all, Thanks for this development, it something that I was looking to found. And already it looks very promising!

I'm wondering if you plane to implement the "Update job" command.

In the case where you have already add a job in a queue (ADDJOB); the job was not already ACK and you want to change the "value" of this job or an option (Timeout, DELAY...), without changing the JobId.  

For this usecase, I think it should be interesting to have an UPDATEJOB command.

```
UPDATEJOB jobid value [options]
```

What do you think?

**Comment by antirez** [comment]
Thank you for the kind words @cedriclam. Such an option is kinda against Disque philosophy of immutable jobs replicated into different nodes. For this to work we would need to have the job to be constantly merged between nodes, and probably also logical clocks in order to resolve conflicts, since it is possible to update a job when certain nodes that own a job copy are not reachable. The current strength of the design is the simplicity that we have because of the fact jobs are immutable if not for their state.

However certain jobs metadata which are not really part of the job may be updatable via certain commands. For example in case we really provide a way to delay the re-queueing of a certain amount of time, but that would just affect the scheduler of the nodes that are available in a given moment, not the job data itself.

Closing for now since I see this very "far" from where we are today. Perhaps in the future such a thing will return on the table when there big picture of how this would fit is more clear. Thanks for the contrib.

**Comment by djanowski** [comment]
I wonder if `COPYJOB` (with new ID, overriding some attributes) would also help for the `ACKJOB + ADDJOB` technique described in #43.

```
COPYJOB <job-id> [QUEUE <queue>] [DELAY <delay>] ...
```

Not suggesting this is super important right now :)

**Comment by antirez** [comment]
@djanowski the problem with atomicity with an AP system like Disque is that is an illusion... :-) Not something you can really achieve under failures, so not worth bothering at all IMHO. And the need to change job parameters is fundamentally against the design as expressed multiple times (job immutability and so forth) and without a clear use case, especially now that there is `WORKING` that is going to be merged. So My feeling is that for now to delete the old job and add a new one is the way to go when really a job modification is needed. If the future will prove the contrary, it is possible to change idea, but today certain things really feel premature to me. Thanks.

**Comment by djanowski** [comment]
For sure, I just wanted to leave the note here in case anyone else finds this in the future. Thank you!
