### ISSUE TITLE
Implement QSTAT (was: QSTAT, SCANJOBS, and other queue introspection commands)

### ISSUE THREAD

**Issue by VojtechVitek** [antirez/disque#48]
`QLEN <queue>` gives me the number of jobs that has `state==queued`.

How can I list jobs that has `state==active`?

**Comment by antirez** [comment]
Hello, Disque is currently lacking from the point of view of introspection capabilities. There are different things we can do, simultaneously, to cover different use cases:
1. Have per queue counters about jobs in all the possible states. So with the `QSTAT` commands it is possible to get this parameters. The `QSTAT` command was already planned, see the README.
2. Implement the `SCANJOBS` command so that is also possible to scan for jobs in all queues setting specific parameters. This would be similar to Redis `SCAN`, so a non blocking, cursor based iterator, that may repeat elements multiple times, but guaranteed to enlist all the elements at least one time.

So renaming this issue to reflect this, and hopefully I'll be able to do some work in this area ASAP. The `QSTAT` thing is conceptually simple but requires some non-trivial reworking of the internals so that state changes are centralized in a way that makes it easy to take the count. It is not sane to add explicit counts every time we currently imperatively change the state with assignments.

**Comment by VojtechVitek** [comment]
Can we have something like `QLEN <queue> [STATE=state]`, eg.:
- `QLEN <queue>`
- `QLEN <queue> STATE=queued`
- `QLEN <queue> STATE=active`

And similarly, what would you think of listing the jobs from the queue, eg.:
- `QLIST <queue>`
- `QLIST <queue> STATE=active`

**Comment by justincase** [comment]
With regards to `QLIST` I think that functionality will be implemented by `JSCAN` similar to `QSCAN`. A state filter would be nice.

**Comment by antirez** [comment]
Hello @VojtechVitek, @justincase. To have a list of jobs in different states would add up the memory requirements, so as @justincase suggested `QLIST` is going to be addressed using the `JCSAN` iterator. However this does no solves very well getting just the count of jobs in a queue in a particular state, so either the feature will be provided by other means by taking counters in the queue for jobs on each state, or skipped at all in favor of a single global counter about jobs in each state. Still not clear since there are trade offs in the implementation side... Probably in the end we'll always have a registered `queue` structure if there is at least one job for this queue, even if not in `queued` state, and as a result we may add fields in the `queue` structure taking different metrics and stats: jobs in different states, instantaneous rate of jobs created/consumed, and so forth.

**Comment by antirez** [comment]
JSCAN implemented. Still a long way to make Disque truly observable but it's a big step forward.

**Comment by VojtechVitek** [comment]
Awesome, I will check that out. Thank you @antirez!

**Comment by antirez** [comment]
Keeping this open since we don't have QSTAT yet. Renaming the issue accordingly.

**Comment by antirez** [comment]
Initial proposal for QSTAT. It should be able to report:
- Rate of jobs locally produced and consumed (jobs/sec).
- Idle time.
- ctime.
- Current source nodes for this queue.
- Queue state (paused in/out... see the PAUSE command proposal).
- Number of clients blocked for this queue right now.

The reply should be in the form of an Array consisting of key value key value ... pairs.

**Comment by antirez** [comment]
Implemented. Closing.
