### ISSUE TITLE
Guarantee message availability in at-most-one mode ?

### ISSUE THREAD

**Issue by vjeantet** [antirez/disque#5]
Hello 
The readme says that no copy is done around nodes when we are in an at-most-one mode.

What happen if the node crash ?

"""
The at most once semantics is a trivial result of using a retry time set to 0 (which means, never re-queue the message again) and a replication factor of 1 for the message (not strictly needed, but it is useless to have multiple copies of a message around if it will be delivered at most one time). 
"""

**Comment by antirez** [comment]
When the node crashes, the message is lost since it is the only way to guarantee the _at most once_ delivery guarantee. However in the case of a controlled restart of a node, the message is not lost, since the `SHUTDOWN REWRITE-AOF` sequence together with the AOF option to load the full state the next restart, are able to provide atomicity guarantees about the state.

**Comment by vjeantet** [comment]
Thanks.

**Comment by antirez** [comment]
You are welcome.
