### ISSUE TITLE
Possible confusion with Unix ctime

### ISSUE THREAD

**Issue by justincase** [antirez/disque#53]
In the context of a job's metadata, `ctime` is the creation time. Most Unix systems today [refer `ctime` to mean `change time`](https://en.wikipedia.org/wiki/Stat_%28system_call%29#ctime). Perhaps we can change it to `creation-time` instead?

**Comment by antirez** [comment]
Hello @justincase, the name it is also used in other ways like in the libc `ctime()` call. I think that since it's an internal data structure and we clearly specify what it is in the context of the source code (in job.h), it should not be an issue. However if we'll ever happen to directly refer to the ctime in the documentation, it's better to call it the _job creation-time attribute_ or alike indeed, but in the context of people touching the Disque source code, it will be clear after a second what it is, so better to type less when coding :-) Thanks.
