### ISSUE TITLE
Document re-queue behavior in regard of message sorting in the queue

### ISSUE THREAD

**Issue by VojtechVitek** [antirez/disque#63]
@antirez What's the default behavior for `REQUEUE` (or planned `NACK`, see #43)? Does it `push_back()` or `push_front()` the job to the queue? Imho, it should `push_front()`, so it's processed asap (with higher priority). Thanks for your answer.

**Comment by antirez** [comment]
Hello @VojtechVitek, it's neither of the two :-) The message is inserted in the local queue in the right position according to its ctime, so if it is the older message, it will likely be pushed as the first to process, if there are other re-queued messages or other messages that are older because never fetched again, it is inserted in the right position. This should be documented indeed... Thanks for asking.

**Comment by antirez** [comment]
Done

**Comment by VojtechVitek** [comment]
Awesome, thanks! :+1:
