### ISSUE TITLE
Pause a queue

### ISSUE THREAD

**Issue by justincase** [antirez/disque#70]
When temporarily wanting to halt a queue from being processed it would be nice to be able to pause and resume (or open/close) a queue. This would be easier than shutting down all workers.

**Comment by antirez** [comment]
Hello @justincase, for the distributed nature of Disque that may be hard, since other nodes may accept the messages anyway. However, assuming we can reach all the nodes in the cluster, how should this work? The broker should reply, like, `-PAUSED Please try later` or something like that?

In such an API I would prefer the stop to be actually a timer, so that if nothing happens in the next `N` seconds, as specified by the `PAUSE` command when executed, the queue automatically unblocks.

Going further in the details:
- `PAUSE` creates an empty queue if called in the context of a node where it does not exist.
- Paused queues are never garbage collected.
- There is a new field in the queue like `blocked_till` with the unix time at which the queue will unblock from the pause, or just `0` if the queue is not blocked.

This is just a design sketch to see if we are talking about something similar. Thanks.

**Comment by justincase** [comment]
Hi @antirez, that sounds good. Perhaps we can include the `blocked_till` timestamp or `<seconds left>` in the reply? As you mentioned the AP nature of Disque does make it rather difficult. I'm not sure on the best way to handle that. I'd like a non-propagating option as well though (to pause a queue on a single specific node).

I'm also considering a `PAUSE` mode that blocks new jobs. That would allow for a graceful node shutdown after all jobs are processed while not accepting new ones.

**Comment by mathieulongtin** [comment]
There is a use case for controlling both side of the queue independently: refuse new jobs and/or don't give jobs to workers. This would likely be used mostly for maintenance. 

For GETJOB, if all the queues requested are paused on the reading end, raise an error "-PAUSED Please try later". Otherwise, just wait for the active queues.

A timeout would be nice, but I wouldn't bother with it if it causes extra complexity. For having used Qless for over two years now, pause came in handy for maintenance and some flow control, but whatever process triggered it can also remove it.

**Comment by antirez** [comment]
Thanks for the hints. Based on what you wrote, a new proposal.

The feature would be exposed via a `PAUES` command:

```
PAUSE <queue-name> [option option ... option]
```

Options:
- `IN` -- Set the queue as paused for incoming messages.
- `OUT` -- Set the queue as paused for outgoing messages.
- `ALL` -- Same as IN + OUT.
- `NONE` -- Clear the pause if any, both IN and OUT.
- `STATE` -- Query the current paused state and reports one of the strings "in", "out", "all", "none".
- `BCAST` -- Broadcast the PAUSE command to other nodes.

Behavior: when a queue is paused in input:
- It no longer accepts new jobs with ADDJOB, reporting a `-PAUSED` error.
- It no longer accepts other jobs from other nodes. Basically it refuses to participate in synchronous replication with other nodes.
- It still asks for messages to other nodes via nodes federation, if there are clients blocked into the queue, since serving the clients is an output operation.
- It does not allow jobs to re-queue after the retry time in this node.
- It discards ENQUEUE messages received via the cluster bus from other nodes trying to do an external replication targeting our queue.

When a queue is paused in output:
- It no longer delivers jobs to clients, behaving exactly like if the queue was empty, so clients will block even if jobs are available in the queue and even if they are actively added.
- It no longer replies to requests for jobs in the context of the cluster federation, so the node no longer acts as a source for messages for other nodes.

When the `OUT` block is cleared, workers pending for a given queue are immediately served if possible.

Normally when a `PAUSE` command is sent, it has only local effects, unless the `BCAST` option is also provided. In such a case all the other reachable nodes are notified. However partitioned nodes will not be automatically notified.

Paused queues are never garbage collected even when empty otherwise the state would be lost. Must be unblocked first.

The `QSCAN` command will be extended in order to be able to filter queues having a particular paused state. The `QSTAT` command must be provided in order to test for a queue state. There is an issue for `QSTAT` already open. Updating it with this information.

Implementation details:
- Disque should call signalQueueAsReady() when a queue is unblocked, so that clients blocked on the queue will be unblocked if there are jobs available.
- Jobs that are scheduled to be queued should not be queued if the queue is paused in input. Should instead pospone the timer to try again in `retry` time.

Important things to document:
- Jobs with a delay and a retry set to 0 that were received _before the queue was paused_, will still get queued even if the queue is paused  in input, otherwise they would be lost.

**Comment by mathieulongtin** [comment]
This is great!

**Comment by djanowski** [comment]
I'm liking this. However, what's the use case for replying with an error, instead of blocking, when a queue is paused for consumption?

**Comment by antirez** [comment]
Damian: the queue may be blocked only in a given node, so the worker should be able to continue elsewhere in theory? But actually is a strange use case since in order to gracefully exclude a node we have a specific feature in place, so why to use this? Maybe we should block as you suggest. Any other opinion?

**Comment by mathieulongtin** [comment]
I agree, from a worker perspective, a paused queue is the same as an empty queue. If a worker needs to worry about that, it can check the queue status after the timeout.

**Comment by djanowski** [comment]
I'm thinking replying with an error may force more complexity on the client for something that is seldom used.

If a client wants to be very smart, then they could check the state of the queue after a timeout. So:
- GETJOB
- When timeout occurs, check if queue is paused
- If so, and being very smart, try the same queue on a different node

But simple clients should be able to go about their business when a queue is paused, just as if there were no jobs to process.

**Comment by antirez** [comment]
I agree, updating the proposal accordingly, thanks for expressing your POV.

**Comment by antirez** [comment]
About the above specification, what about dropping the fact that a paused queue makes the node refusing the replication of that job? Checking better, seems an orthogonal concept. One thing is replicating a job for another node... one thing is pausing a queue. When a job is replicated is not put into the queue normally.

**Comment by antirez** [comment]
Mm... no thinking again about this, allowing replication of external jobs of a queue which is paused in input opens a lot of problems. Better to stick with the original proposal.

**Comment by antirez** [comment]
Proposal implemented and documented. Closing.
